"""save states

Revision ID: 5721e748ee50
Revises: 475e88f58ee4
Create Date: 2022-05-20 16:51:28.064137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5721e748ee50'
down_revision = '475e88f58ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('save',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('asia', sa.String(length=64), nullable=True),
    sa.Column('north_america', sa.String(length=64), nullable=True),
    sa.Column('europe', sa.String(length=64), nullable=True),
    sa.Column('africa', sa.String(length=64), nullable=True),
    sa.Column('south_america', sa.String(length=64), nullable=True),
    sa.Column('australia', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('save')
    # ### end Alembic commands ###
